name: Update AoC Badges
on:
  workflow_dispatch:                             # allow to manually start the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4                # clones your repo

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 894384                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          file: aoc23/README.md

      - uses: stefanzweifel/git-auto-commit-action@v5     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: '*.md'
